<<<<<<< HEAD
# Generated by Django 3.2.11 on 2022-01-17 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='V4_Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('ssd', models.BooleanField(default=False)),
                ('processor', models.CharField(choices=[('', '----'), ('AMD Dual Core Ryzen', 'AMD Dual Core Ryzen'), ('Intel Dual Core', 'Intel Dual Core'), ('Apple M1 Chip', 'Apple M1 Chip'), ('Intel 8 Core', 'Intel 8 Core'), ('Core i3', 'Core i3'), ('Core i5', 'Core i5'), ('Core i7', 'Core i7'), ('Core i10', 'Core i10')], default=None, max_length=50)),
                ('color', models.CharField(choices=[('', '----'), ('Black', 'Black'), ('Gray', 'Gray'), ('Space Grey', 'Space Grey'), ('White', 'White'), ('Red', 'Red'), ('Pink', 'Pink'), ('Denium Blue', 'Denium Blue')], default=None, max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v4_laptops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stored'],
            },
        ),
    ]
=======
# Generated by Django 3.2.11 on 2022-01-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V4_Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('ssd', models.BooleanField(default=False)),
                ('processor', models.CharField(choices=[('', '----'), ('AMD Dual Core Ryzen', 'AMD Dual Core Ryzen'), ('Intel Dual Core', 'Intel Dual Core'), ('Intel 8 Core', 'Intel 8 Core'), ('Core i3', 'Core i3'), ('Core i5', 'Core i5'), ('Core i7', 'Core i7'), ('Core i10', 'Core i10')], default=None, max_length=50)),
                ('color', models.CharField(choices=[('', '----'), ('Black', 'Black'), ('Gray', 'Gray'), ('White', 'White'), ('Red', 'Red'), ('Pink', 'Pink'), ('Denium Blue', 'Denium Blue')], default=None, max_length=50)),
            ],
            options={
                'ordering': ['stored'],
            },
        ),
    ]
>>>>>>> 46c359c8d81b0e9100a09be49b727912972171cc
