# Generated by Django 3.2.11 on 2022-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_laptops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v4_laptop',
            name='color',
            field=models.CharField(choices=[('', '----'), ('Black', 'Black'), ('Gray', 'Gray'), ('Space Grey', 'Space Grey'), ('White', 'White'), ('Red', 'Red'), ('Pink', 'Pink'), ('Denium Blue', 'Denium Blue')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='v4_laptop',
            name='processor',
            field=models.CharField(choices=[('', '----'), ('AMD Dual Core Ryzen', 'AMD Dual Core Ryzen'), ('Intel Dual Core', 'Intel Dual Core'), ('Apple M1 Chip', 'Apple M1 Chip'), ('Intel 8 Core', 'Intel 8 Core'), ('Core i3', 'Core i3'), ('Core i5', 'Core i5'), ('Core i7', 'Core i7'), ('Core i10', 'Core i10')], default=None, max_length=50),
        ),
    ]
