# Generated by Django 3.2.11 on 2022-01-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_laptops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='V1_Laptop',
        ),
    ]
