# Generated by Django 3.2.11 on 2022-01-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_laptops', '0002_rename_laptop_v1_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1_laptop',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Gray', 'Gray'), ('White', 'White'), ('Red', 'Red'), ('Pink', 'Pink'), ('Denium Blue', 'Denium Blue')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='v1_laptop',
            name='processor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Corei3', max_length=50),
        ),
    ]
