# Generated by Django 3.2.11 on 2022-01-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='modelnumber',
            field=models.CharField(max_length=50),
        ),
    ]
