# Generated by Django 3.2.11 on 2022-01-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_alter_laptop_modelnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='modelnumber',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
