# Generated by Django 3.2.11 on 2022-01-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V2_Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('ssd', models.BooleanField(default=False)),
                ('processor', models.CharField(choices=[('', '----'), ('AMD Dual Core Ryzen', 'AMD Dual Core Ryzen'), ('Intel Dual Core', 'Intel Dual Core'), ('Intel 8 Core', 'Intel 8 Core'), ('Core i3', 'Core i3'), ('Core i5', 'Core i5'), ('Core i7', 'Core i7'), ('Core i10', 'Core i10')], default=None, max_length=50)),
                ('color', models.CharField(choices=[('', '----'), ('Black', 'Black'), ('Gray', 'Gray'), ('White', 'White'), ('Red', 'Red'), ('Pink', 'Pink'), ('Denium Blue', 'Denium Blue')], default=None, max_length=50)),
            ],
            options={
                'ordering': ['stored'],
            },
        ),
    ]
